### ISSUE TITLE
API requires login on Deta since last update

### ISSUE THREAD

**Issue by TheShovel** [lemonyte/wastebin#5]
Making API requests requires logging into my Deta Space account since the last update.
I need my app to be able to temporarily upload files, and I can't do that anymore.

**Comment by TheShovel** [comment]
Right now I can just run a dev build with `/api/new*` added to the public routes. I am curious why this got changed though.

**Comment by lemonyte** [comment]
I decided creating pastes was for the owner of the instance only, otherwise anyone would be able to add content into anyone's instance. If you want to use the API to create pastes, you can create an API key in the app's settings (I will add this setting to the Spacefile).

The last update was the final bit of migration from the old Deta Cloud model to the new Deta Space model, so the entire app is no longer a public centralized site.

**Comment by lemonyte** [comment]
I've released a new version with API keys enabled, closing this issue now. Thanks @TheShovel!

**Comment by TheShovel** [comment]
Alright. Thanks!
