### ISSUE TITLE
Possible to create pastes without loging in?

### ISSUE THREAD

**Issue by driftywinds** [lemonyte/wastebin#6]
I realised I can only create new pastes if I login through Deta, so I was wondering if an option to turn this off could be added so that anyone who opens my Wastebin can create their own pastes?

**Comment by lemonyte** [comment]
It isn't possible with the version installable from Deta Discovery, since the routes used to create pastes are configured as private. If you are fine with the risk of abuse, you can create your own build of the project by forking the source code and changing the `public_routes` section of the Spacefile to include all routes.

```yaml
    public_routes:
      - "*"
```

Developer docs for creating your modified project instance: https://deta.space/docs/en/build/new-apps

**Comment by driftywinds** [comment]
> It isn't possible with the version installable from Deta Discovery, since the routes used to create pastes are configured as private. If you are fine with the risk of abuse, you can create your own build of the project by forking the source code and changing the `public_routes` section of the Spacefile to include all routes.
> 
> ```yaml
>     public_routes:
>       - "*"
> ```
> 
> Developer docs for creating your modified project instance: https://deta.space/docs/en/build/new-apps

I will try doing this but I don't code so lets see if it successful. Is it possible for you to make this a toggellable setting and release an update to Deta? That would be a godsend if possible.

**Comment by driftywinds** [comment]
Alright I have released a version of this app [here](https://deta.space/discovery/@driftywinds/wastebindw) in case anyone looking at this issue also wants free access to creating pastes. 

It would still be cool if you could add the ability to do this as a toggellable setting though!

**Comment by lemonyte** [comment]
Unfortunately that would require implementing my own auth, instead of using Deta's built-in functionality, since it is not possible to dynamically change whether a route is public. Maybe in the future this will be possible.

Since this project is in maintenance-only status right now, it's highly unlikely that I will implement this, but contributions are welcome as always!
